local set = vim.opt

-- Opts v1.1
set.backup = false
set.clipboard = "unnamedplus"
set.cmdheight = 1 -- Previously 2
set.completeopt = { "menuone", "noselect" }
set.conceallevel = 0
set.fileencoding = "utf-8"
set.hlsearch = true
set.ignorecase = true
set.mouse = "a"
set.pumheight = 10
set.showmode = false
set.showtabline = 4
set.smartcase = true
set.smartindent = true
set.splitbelow = true
set.splitright = true
set.swapfile = false
set.timeoutlen = 1000
set.undofile = true
set.updatetime = 300
set.writebackup = false
set.expandtab = true
set.shiftwidth = 4
set.tabstop = 4
set.cursorline = true
set.number = true
set.relativenumber = false -- Previously False
set.numberwidth = 4
set.signcolumn = "yes"
set.wrap = true -- Previously False
set.linebreak = true
set.scrolloff = 8
set.sidescrolloff = 8
